dist: xenial
language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy3"

install:
  # Ensure modern pip/etc to avoid some issues w/ older worker environs
  - pip install pytest
  - pip install coverage
  - pip install pytest-cov
  - pip install mock
  - pip install codecov # For codecov specifically
  - pip install -e .

script:
  - pytest --cov=wait_for_it tests/

env:
  - CODECOV_TOKEN="919258c7-ed4b-463f-973a-68fc7a081d2d"

after_success:
  - codecov

deploy:
  provider: pypi
  user: studioj
  password:
    secure: UNfdRbvidI4DadUnuAz2nJzNujbBC7gMhIN6byhYgBs1s4a8+xaO6b7kzQ+p60D4cC0Q9HacQLzWWy7QxCXOaWq42kOxqJhkdIUx5xzQeB11MsQD5YFxs7DHn1mAFUoLk93QjzNniC1pAdIr5QiTlL5xV6Txmjk0qPexGpJNHLjZI8gEuKKW8WX3kYHi0gcrxUmWzgooRkPzJAFmajIvumWjZRFuVltam9rXbMCPBtTGsYE3bUe8OHeFHgmgKZdHUd+7HuiQwFLD4weDWPBc+V+Y4sSyPIj6RRrvZzZXGHJ4eO+Xw4HAE23ruQ9b62OnnTD/oYuyHoXgxc/JJoYG9Q6z4q4E4GBHi+w4WhKgLIoRiKq2Ge4LMosr2rrL0xkmJb2Nna5h+bd4L8KBMUoEU43Ev9f8ke7We7J3FItrKyCRgsVeVYTHSjTZNBeSzOGan/QacvyikObvbBwLLurK0T5d2ug7x/3lmUQGFpVa9ZsrH5SGc4GCbhGG7Nc62qZ87RGaVJ0M5WPdPUsOu5fqP+MU9lOeiHUQcnBnlSrxxU+Hmi6N0Q5U5VKHNTenUMfVBCB7+HsZHtoJV6Lkx1f2DuCvxFqap2M0uobLz3jZHP/WmcyPhB+ufda7nt717ZiLeWDktcqmr6sTG7dFx/y68R2UdmxKypBrwwUucuS7NUI=
  on:
    branch: release
