dist: xenial
language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy3"

install:
  # Ensure modern pip/etc to avoid some issues w/ older worker environs
  - pip install pytest
  - pip install coverage
  - pip install pytest-cov
  - pip install mock
  - pip install codecov # For codecov specifically
  - pip install -e .

script:
  - pytest --cov=wait_for_it_to tests/

env:
  - CODECOV_TOKEN="919258c7-ed4b-463f-973a-68fc7a081d2d"

after_success:
  - codecov

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: studioj
  password:
    secure: OoUxKKQ3p7I7FNqSwH0sUyIFXwNTiam6BwA+z6BM/eKWMyceNVY8WKMIf7u4QntMnuo2RYASK1HTbbYyYXd5evbaZlYOaCIxhfkyI+V22hcM1RMBdEKFF/Eg/HOJohTIFILFbiaic0ND+I+3d17uM668ug4un/uzGMQdXntSU7Hegkl5JAEmBR6GeUQE0jrHYpU7fu7o+AM8yB7pw3MCcYgx2t9lNdPPKVpMwMYDlAyeNVbjBa11W4McpDxjg+Xodl6jV8MK/nJn1HLwrX5+X5zrJNNIXEZx02YpfTVi0+cWw4oEEsnajOP9YMWi6Sv9hXZKM9bHjCiBGQCpFH8azGr1vRz890KIJwJCk2UvrnGz4Uw4UBzTER0SW16ILPVO90R+QbPnXd6SP7sWoRHmfD0G5YEm+5duMmMpahGKpqjFHnVAdU/Wk5JbRqRTtb4cthiAsyVODgGAoj7+dl5NHadzTYC3JvWpRTlZzDTi+C2perbFFF/bDp7Q1/d1ieIcvciYxeie8WBwvQdmt3LwsPIU3deJb9aPbKLBx4YlyGXSVluFgpScHB63mSDLXMSxXiHEsBeYvagHjrraZqQvIE3evDGSy7IvawyD6Mfj2RxeT8oj1+MXW5q93IAV6+aVJ5+9rBa+GKTx5kmNCP1QYd87bc8gIxdT/gGM8Uuso30=
  on:
    branch: release
  verbose: true

