dist: xenial
language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy3"

install:
  # Ensure modern pip/etc to avoid some issues w/ older worker environs
  - pip install pytest
  - pip install coverage
  - pip install pytest-cov
  - pip install mock
  - pip install codecov # For codecov specifically
  - pip install -e .

script:
  - pytest --cov=wait_for_it_to tests/

env:
  - CODECOV_TOKEN="919258c7-ed4b-463f-973a-68fc7a081d2d"

after_success:
  - codecov

deploy:
  provider: pypi
  user: studioj
  distributions: "sdist bdist bdist_wheel"
  password: r63L220hL25vMKVIo9JMUZYZJ0owQiJf+w5itPqSGbAC2jLV9eNfMIe0YxfduNRwtABr5mzdjg+jNtb4NRIrg7HOw4jjpyE4mXojkFc+Pgum8wHnXzcRx44yWnBOLBx8nQHT+AeXfVa8jTp/zm+cVRkmVq8sAodqSWH7froYEgBhU7i5u9vvJp9FQOAFdcq4uxncULIPY2P9zYp0H+vVRkJ9HSTefU9oIfiySFgQy/bOPwxDfGBwBCKFtp5Ug79QXMWdCsT+Daiqmz4YugI1kFMNlveTp4PQ1uh+lkqCBlvCeGh5y5+qbv/tRKSqUA10xrXfxpVdYwYwMKhn5pw3CoxKC33iflafsL3P++yaRA6lvb601QJeSHzvm8G2Qd99mK2ZPW4gASHiLMSNN5yf2P0+LGz67lsF1GYHSdOmaUhNx46rZ2lUMGTIkFXH754pbg2LPULowVs19WQ664ajQR4B2fterJ4WlRExnomUX0T0ugpETejiYAqXFBmH7OzXFe6oASJC8+IEYTpTuR5t9jCSDKtzY1FYYuJoTMHJx2rKR/bhZXEk+04Ty8PWhCxaRnlLH7brd2XNF/lYumJL7i0TrkqKZGcKvZXVxs0O+MWrvaxiXMSDM2Edvhc8tMN8d70bsX0ANqUYRpB+aDgpBqw9z4IBQ6ooT6dx5NKXydk=
  on:
    branch: release
  repo: studioj/wait_for_it

