dist: xenial
language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy3"

install:
  # Ensure modern pip/etc to avoid some issues w/ older worker environs
  - pip install pytest
  - pip install coverage
  - pip install pytest-cov
  - pip install mock
  - pip install codecov # For codecov specifically
  - pip install -e .

script:
  - pytest --cov=wait_for_it_to tests/

env:
  - CODECOV_TOKEN="919258c7-ed4b-463f-973a-68fc7a081d2d"

after_success:
  - codecov

deploy:
  provider: pypi
  user: studioj
  password:
    secure: i7MXm0iL+J8Nt9uJ6ri9XbY169vR6cD+vcqqxd2hzv8rL1jh0Ny/hJYKcblcfxesv5oxcu2Zid61roWKqmWzLdSN23EEnhxuLbPTWVZxOzD0l4He81gekrwpjN0eegsS0P7R2+LZjV1mqlDq8kukmq4lMMOHHoQwKxclimFZdTM7PrqMiKgGnGRHPoBPJdb6kJeT5uCydV8eWX/23/BomtYnbUVGi46JKcv2X1qAuD/DIhcjOJXMh6YXHIvFXijeaplpSYvd4gNCsKte57lluRyxZ9bqxlvedW796U/S9UhuIMsw5+Vu3ioVz2Ah310phSzSCSRNgH4OcNVpAxi9q2Mz+P8EH1LCL2pnNSiKGTiphyvmVvNqF70amCxW/0C1ElcThkCg+3hqYv+19glyeAkyZXJPOy9WXsjyV2TMA2u1MXXsAaUN5X8riIXiyZspF0XNyrDAnM2Ha9edqYKoiJOQ8vaGGTVC4Jt5FPjoe/qfFNK7p++p1njSZa/+vNHjmZbgo90vi3r0iTShk+USKh3YV81FbHmZaPQbQJUA7uAFD7J0Wrce7PnuEJ/yfJ4XNRuKvOUiFmLfsD+ZiG4z+SUmb7BPDDp8FTjiXp+omgDjmpV4LsebJrez4JaWYkpeKsyaq0/SSZAaReTWunXIDFoyQOElrz1NPrBLEo1oTB4=
  on:
    branch: release
