dist: xenial
language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy3"

install:
  # Ensure modern pip/etc to avoid some issues w/ older worker environs
  - pip install pytest
  - pip install coverage
  - pip install pytest-cov
  - pip install mock
  - pip install codecov # For codecov specifically
  - pip install -e .

script:
  - pytest --cov=wait_for_it_to tests/

env:
  - CODECOV_TOKEN="919258c7-ed4b-463f-973a-68fc7a081d2d"

after_success:
  - codecov

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: studioj
  password:
    secure: "pwJcLHiJmBoCL5Q4neAQ6haIcyCowSCfR7jQPrEFUezwKfliDmSNUAXTLsFn9G/iF/WqHDSlikvY7mJCB036k/ccz1uZTmFIe9S8xHSSzP1KrR3OoY7S8h3EPFK/nUGo/X23KL5s1nfk61BTV1kEgczVzKDV5pESCCFoWgQAXRLZkDYgRKDqm+rez1v++Knn7CuxdbzGQl5IKj3CntORlswGXX/j4NjjkkqQwzQklsvxNNiNBOj9QRKU60xzxT19JywDVfU4zCBKejPlcvnJKA6dKimT4M3HdcDdI4g9CpOFVKU4wZxWuNM3OSYDtLkWK+q0yvUlXQcVd54Pl3lsIwB7dezg7G/Gqzg8aDl9hS7AXihHYP98n87cLl93cB7PO9aa7VZNedibUxBSbpsXxkRcX83PYKDn9FHCO4ZZKgHRl1sVEkKXu5ex+7Xwwz9ExHv4UUQ0enKdEutbsraLhh68GtOynBohMa7t9hoqWrtE7G+Wa+FBglTHTKozEuMEewbqlQr6rSULhFB9XUPMPSKrCfdwSHkGtaSLOs/CLtDGgGXDhwhwufaOOWGcxHRlcsvPLUaF/ilaI2y56OCJsY76z32zfX6sRGIhaF71xhkfUSsKccYG5NHztVN3wPvvSY+xQQJA+qIsezuJ1w5d4RHoct8lB9kKuaK2YY744No="
  on:
    branch: release

