dist: xenial
language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy3"

install:
  # Ensure modern pip/etc to avoid some issues w/ older worker environs
  - pip install pytest
  - pip install coverage
  - pip install pytest-cov
  - pip install mock
  - pip install codecov # For codecov specifically
  - pip install -e .

script:
  - pytest --cov=wait_for_it_to tests/

env:
  - CODECOV_TOKEN="919258c7-ed4b-463f-973a-68fc7a081d2d"

after_success:
  - codecov

deploy:
  provider: pypi
  user: studioj
  password:
    secure: GTyYlpNTQ95LqPCtgqlSfDOleMFwQ0ijCHRkUYYmSKpGftzGBDXfwcnxd4pqFDQNS2DcHwF43PnBECrcPVrM/ryjPkdloCnLfv8+oKnjqh3guEsRKfNBcXWqRnL4DjuR/T66w3BCNs3DUFBbmO+71Ak8vSuMKD0U32n3tNYM/UJZgDR3XLayttC9nOAZJOnrUzs60300KB7457tmZ4TJGTtC7fKGZ99U7P2AsBI0hJi236cicJuzcJeqEcwdZg+o7zW2eohhlGSFirczc3L7sw1H/BaYcRRc1SFggRiBwW+/V9CJjKH9YXu2PXhuezXuu2wA8JcJWugDhOyq4GqRi7uIq4cxyH89Y0ndbIKl2e/vtgWrVLB2LmfI9y9GBdjwOh1Fx8BC7I049BxeWsLfUo45qk0qRqVpFyMl2FrcOPUQdVpaSaIpLTr05hRKM9C1thB3YN0V1Kqna/0v2HViO+flTBOtXIlvVw9GClOPmTvdgGGQwGJ6aGO9MbXQ6fQzIhgtFq3qKoSo/FvGanlqfIs5L9TkRow8y8vHY3P+PexO8kirQzTfo6PlqpB1c6wMuK4kMMp1gyKYUlYSHny84PEhb9LO+BdWGf2s3D53ioynZmMSc4UCtYmc11ktPnMq7zcC78OUE/+Fe7YUUpncXv65ilfxDm4CbCIyofGb1Gw=
  on:
    branch: release
